import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const srcDir = resolve(repoRoot, 'src');
const migrationsDir = resolve(repoRoot, 'supabase/migrations');
const functionsDir = resolve(repoRoot, 'supabase/functions');

const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs']);

function sourceFiles(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return sourceFiles(full);
    return SOURCE_EXTENSIONS.has(extname(full)) ? [full] : [];
  });
}

// src/types/database.ts is generated by `npm run db:types` and names every
// column in the schema, credit_balance included. It is a description of the
// database, not code that writes to it, so scanning it would make this suite
// fail for the one file that is guaranteed to mention everything.
const GENERATED = new Set(['src/types/database.ts']);

const appSources = sourceFiles(srcDir)
  .map((file) => ({
    path: relative(repoRoot, file),
    source: readFileSync(file, 'utf8'),
  }))
  .filter(({ path }) => !GENERATED.has(path));

const migrations = readdirSync(migrationsDir)
  .filter((name) => name.endsWith('.sql'))
  .map((name) => ({ name, sql: readFileSync(join(migrationsDir, name), 'utf8') }));

const allMigrationSql = migrations.map((m) => m.sql).join('\n');

/**
 * T07 acceptance: "No 'check then deduct' logic exists anywhere in application
 * code", and ARCHITECTURE.md §6.5 — credits move through spend_credits and
 * grant_credits or they do not move.
 *
 * This is a static assertion over the source tree rather than a list someone
 * has to remember to update, so it keeps holding as T20A, T23, T24 and T35 add
 * the routes that will actually spend and grant.
 *
 * It is deliberately about what the APPLICATION does, not about what the
 * database permits. service_role still holds INSERT on credit_ledger and UPDATE
 * on profiles (T05, T06), so this rule is a convention the tests enforce rather
 * than a privilege the database enforces — see section 4 of the T07 migration
 * and ADR-0014 for why narrowing those grants belongs to T26 rather than here.
 */
describe('credits move only through the T07 RPCs', () => {
  it('finds source files to check (guards against a broken walker)', () => {
    expect(appSources.length).toBeGreaterThan(5);
  });

  it('never writes profiles.credit_balance from application code', () => {
    const offenders = appSources.filter(({ source }) => /credit_balance\s*:/.test(source));
    expect(offenders.map((f) => f.path)).toEqual([]);
  });

  it('never inserts into credit_ledger from application code', () => {
    const offenders = appSources.filter(({ source }) =>
      /from\s*\(\s*['"`]credit_ledger['"`]\s*\)\s*[\s\S]{0,80}?\.(insert|upsert|update|delete)\b/.test(
        source,
      ),
    );
    expect(offenders.map((f) => f.path)).toEqual([]);
  });

  it('never reads a balance in order to decide whether a spend is affordable', () => {
    // The shape §6.5 forbids: a balance read and an arithmetic comparison
    // against it in the same file. The RPC does this under a row lock; anything
    // above the database doing it is a race by construction.
    const offenders = appSources.filter(
      ({ source }) =>
        /credit_balance/.test(source) && /credit_balance\s*[\s\S]{0,40}?[<>]=?/.test(source),
    );
    expect(offenders.map((f) => f.path)).toEqual([]);
  });
});

/**
 * `supabase/functions/*.sql` is the reference copy of the SQL that
 * `supabase/README.md` points readers at. The migration is what actually
 * reaches a database, so a reference copy that has drifted is worse than none:
 * it is a confident, wrong answer to "what does spend_credits do?".
 *
 * Rather than trusting nobody edits one without the other, every mirror file is
 * asserted to appear verbatim inside a migration.
 */
describe('supabase/functions mirrors the migration exactly', () => {
  const mirrors = readdirSync(functionsDir)
    .filter((name) => name.endsWith('.sql'))
    .map((name) => ({ name, sql: readFileSync(join(functionsDir, name), 'utf8') }));

  it('finds the three T07 function sources', () => {
    expect(mirrors.map((m) => m.name).sort()).toEqual([
      'credit_ledger_idempotent_match.sql',
      'grant_credits.sql',
      'spend_credits.sql',
    ]);
  });

  it.each(mirrors)('$name appears verbatim in a migration', ({ sql }) => {
    // Strip the file's own header — the leading run of comment and blank lines
    // — and require everything after it to be present character for character.
    const body = sql.replace(/^(?:\s*--[^\n]*\n|\s*\n)+/, '');
    expect(body.length).toBeGreaterThan(200);
    expect(allMigrationSql).toContain(body.trimEnd());
  });
});

/**
 * ADR-004's consequence for T07, asserted against the migration text itself.
 * The pgTAP suite proves the resulting ACL, which is the stronger check; this
 * one proves the statements are in the same FILE as the body, which is the part
 * that stops a later "fix the RPC" migration from silently reopening PUBLIC.
 */
describe('the T07 migration carries its own privilege statements', () => {
  const t07 = migrations.find((m) => m.name.endsWith('_credit_rpcs.sql'));

  it('exists', () => {
    expect(t07).toBeDefined();
  });

  it.each(['spend_credits', 'grant_credits'])(
    'revokes %s from PUBLIC, anon and authenticated in the same file as the body',
    (fn) => {
      expect(t07!.sql).toMatch(
        new RegExp(`revoke all on function public\\.${fn}\\([^)]*\\)\\s*\\n\\s*from public, anon, authenticated;`),
      );
    },
  );

  it.each(['spend_credits', 'grant_credits'])('grants %s to service_role and nobody else', (fn) => {
    expect(t07!.sql).toMatch(
      new RegExp(`grant execute on function public\\.${fn}\\([^)]*\\)\\s*\\n\\s*to service_role;`),
    );
    expect(t07!.sql).not.toMatch(new RegExp(`grant execute on function public\\.${fn}[\\s\\S]*?to (anon|authenticated)`));
  });

  it('grants the private helper to nobody at all', () => {
    expect(t07!.sql).toMatch(
      /revoke all on function public\.credit_ledger_idempotent_match\([^)]*\)\s*\n\s*from public, anon, authenticated, service_role;/,
    );
    expect(t07!.sql).not.toMatch(/grant execute on function public\.credit_ledger_idempotent_match/);
  });

  it('creates exactly three functions and no more', () => {
    const creates = t07!.sql.match(/create or replace function public\.(\w+)/g) ?? [];
    expect(creates).toEqual([
      'create or replace function public.credit_ledger_idempotent_match',
      'create or replace function public.spend_credits',
      'create or replace function public.grant_credits',
    ]);
  });

  it.each(['credit_ledger_idempotent_match', 'spend_credits', 'grant_credits'])(
    'pins search_path on %s',
    (fn) => {
      // The signature block only — everything between the CREATE and the body
      // delimiter. Matching the whole file would count the header comment that
      // explains the pin and pass whether or not any function carried it.
      const signature = t07!.sql.match(
        new RegExp(`create or replace function public\\.${fn}\\([\\s\\S]*?\\nas \\$\\$`),
      );
      expect(signature).not.toBeNull();
      expect(signature![0]).toContain('set search_path = public, pg_temp');
    },
  );
});
